"""Expand movie model and add recognition history and favorites

Revision ID: 21ce9b3b3b7a
Revises: 6e839fc799ba
Create Date: 2026-04-10 22:26:01.926046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ce9b3b3b7a'
down_revision: Union[str, Sequence[str], None] = '6e839fc799ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recognition_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('movie_id', sa.UUID(), nullable=False),
    sa.Column('media_url', sa.String(length=512), nullable=True),
    sa.Column('confidence_score', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('movies', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('movies', sa.Column('poster_path', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('backdrop_path', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_column('movies', 'updated_at')
    op.drop_column('movies', 'backdrop_path')
    op.drop_column('movies', 'poster_path')
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'description')
    op.drop_column('movies', 'tmdb_id')
    op.drop_table('recognition_history')
    op.drop_table('favorites')
    # ### end Alembic commands ###
